Attribute VB_Name = "ipifcons"
Option Explicit


Public Const MIB_IF_ADMIN_STATUS_UP = 1
Public Const MIB_IF_ADMIN_STATUS_DOWN = 2
Public Const MIB_IF_ADMIN_STATUS_TESTING = 3

Public Const MIB_IF_OPER_STATUS_NON_OPERATIONAL = 0
Public Const MIB_IF_OPER_STATUS_UNREACHABLE = 1
Public Const MIB_IF_OPER_STATUS_DISCONNECTED = 2
Public Const MIB_IF_OPER_STATUS_CONNECTING = 3
Public Const MIB_IF_OPER_STATUS_CONNECTED = 4
Public Const MIB_IF_OPER_STATUS_OPERATIONAL = 5

Public Const MIB_IF_TYPE_OTHER = 1
Public Const MIB_IF_TYPE_ETHERNET = 6
Public Const MIB_IF_TYPE_TOKENRING = 9
Public Const MIB_IF_TYPE_FDDI = 15
Public Const MIB_IF_TYPE_PPP = 23
Public Const MIB_IF_TYPE_LOOPBACK = 24
Public Const MIB_IF_TYPE_SLIP = 28
