Attribute VB_Name = "pdhmsg"
Option Explicit


Public Const PDH_CSTATUS_VALID_DATA = &H0
Public Const PDH_CSTATUS_NEW_DATA = &H1
Public Const PDH_CSTATUS_NO_MACHINE = &H800007D0
Public Const PDH_CSTATUS_NO_INSTANCE = &H800007D1
Public Const PDH_MORE_DATA = &H800007D2
Public Const PDH_CSTATUS_ITEM_NOT_VALIDATED = &H800007D3
Public Const PDH_RETRY = &H800007D4
Public Const PDH_NO_DATA = &H800007D5
Public Const PDH_CALC_NEGATIVE_DENOMINATOR = &H800007D6
Public Const PDH_CALC_NEGATIVE_TIMEBASE = &H800007D7
Public Const PDH_CALC_NEGATIVE_VALUE = &H800007D8
Public Const PDH_DIALOG_CANCELLED = &H800007D9
Public Const PDH_END_OF_LOG_FILE = &H800007DA
Public Const PDH_CSTATUS_NO_OBJECT = &HC0000BB8
Public Const PDH_CSTATUS_NO_COUNTER = &HC0000BB9
Public Const PDH_CSTATUS_INVALID_DATA = &HC0000BBA
Public Const PDH_MEMORY_ALLOCATION_FAILURE = &HC0000BBB
Public Const PDH_INVALID_HANDLE = &HC0000BBC
Public Const PDH_INVALID_ARGUMENT = &HC0000BBD
Public Const PDH_FUNCTION_NOT_FOUND = &HC0000BBE
Public Const PDH_CSTATUS_NO_COUNTERNAME = &HC0000BBF
Public Const PDH_CSTATUS_BAD_COUNTERNAME = &HC0000BC0
Public Const PDH_INVALID_BUFFER = &HC0000BC1
Public Const PDH_INSUFFICIENT_BUFFER = &HC0000BC2
Public Const PDH_CANNOT_CONNECT_MACHINE = &HC0000BC3
Public Const PDH_INVALID_PATH = &HC0000BC4
Public Const PDH_INVALID_INSTANCE = &HC0000BC5
Public Const PDH_INVALID_DATA = &HC0000BC6
Public Const PDH_NO_DIALOG_DATA = &HC0000BC7
Public Const PDH_CANNOT_READ_NAME_STRINGS = &HC0000BC8
Public Const PDH_LOG_FILE_CREATE_ERROR = &HC0000BC9
Public Const PDH_LOG_FILE_OPEN_ERROR = &HC0000BCA
Public Const PDH_LOG_TYPE_NOT_FOUND = &HC0000BCB
Public Const PDH_NO_MORE_DATA = &HC0000BCC
Public Const PDH_ENTRY_NOT_IN_LOG_FILE = &HC0000BCD
Public Const PDH_DATA_SOURCE_IS_LOG_FILE = &HC0000BCE
Public Const PDH_DATA_SOURCE_IS_REAL_TIME = &HC0000BCF
Public Const PDH_UNABLE_READ_LOG_HEADER = &HC0000BD0
Public Const PDH_FILE_NOT_FOUND = &HC0000BD1
Public Const PDH_FILE_ALREADY_EXISTS = &HC0000BD2
Public Const PDH_NOT_IMPLEMENTED = &HC0000BD3
Public Const PDH_STRING_NOT_FOUND = &HC0000BD4
Public Const PDH_UNABLE_MAP_NAME_FILES = &H80000BD5
Public Const PDH_UNKNOWN_LOG_FORMAT = &HC0000BD6
Public Const PDH_UNKNOWN_LOGSVC_COMMAND = &HC0000BD7
Public Const PDH_LOGSVC_QUERY_NOT_FOUND = &HC0000BD8
Public Const PDH_LOGSVC_NOT_OPENED = &HC0000BD9
Public Const PDH_WBEM_ERROR = &HC0000BDA
Public Const PDH_ACCESS_DENIED = &HC0000BDB
Public Const PDH_LOG_FILE_TOO_SMALL = &HC0000BDC
Public Const PDH_INVALID_DATASOURCE = &HC0000BDD
Public Const PDH_INVALID_SQLDB = &HC0000BDE
Public Const PDH_NO_COUNTERS = &HC0000BDF
Public Const PDH_SQL_ALLOC_FAILED = &HC0000BE0
Public Const PDH_SQL_ALLOCCON_FAILED = &HC0000BE1
Public Const PDH_SQL_EXEC_DIRECT_FAILED = &HC0000BE2
Public Const PDH_SQL_FETCH_FAILED = &HC0000BE3
Public Const PDH_SQL_ROWCOUNT_FAILED = &HC0000BE4
Public Const PDH_SQL_MORE_RESULTS_FAILED = &HC0000BE5
Public Const PDH_SQL_CONNECT_FAILED = &HC0000BE6
Public Const PDH_SQL_BIND_FAILED = &HC0000BE7
Public Const PDH_CANNOT_CONNECT_WMI_SERVER = &HC0000BE8


Public Function PdhError(ByVal lngError As Long, ByVal strFunction As String, Optional ByRef errDescription As String, Optional ByVal NoMsgBox As Boolean)
    Select Case lngError
        Case PDH_CSTATUS_VALID_DATA: errDescription = "The returned data is valid."
        Case PDH_CSTATUS_NEW_DATA: errDescription = "The return data value is valid and different from the last sample."
        Case PDH_CSTATUS_NO_MACHINE: errDescription = "Unable to connect to specified machine or machine is off line."
        Case PDH_CSTATUS_NO_INSTANCE: errDescription = "The specified instance is not present."
        Case PDH_MORE_DATA: errDescription = "There is more data to return than would fit in the supplied buffer. Allocate a larger buffer and call the function again."
        Case PDH_CSTATUS_ITEM_NOT_VALIDATED: errDescription = "The data item has been added to the query, but has not been validated nor accessed. No other status information on this data item is available."
        Case PDH_RETRY: errDescription = "The selected operation should be retried."
        Case PDH_NO_DATA: errDescription = "No data to return."
        Case PDH_CALC_NEGATIVE_DENOMINATOR: errDescription = "A counter with a negative denominator value was detected."
        Case PDH_CALC_NEGATIVE_TIMEBASE: errDescription = "A counter with a negative timebase value was detected."
        Case PDH_CALC_NEGATIVE_VALUE: errDescription = "A counter with a negative value was detected."
        Case PDH_DIALOG_CANCELLED: errDescription = "The user cancelled the dialog box."
        Case PDH_END_OF_LOG_FILE: errDescription = "The end of the log file was reached."
        Case PDH_CSTATUS_NO_OBJECT: errDescription = "The specified object is not found on the system."
        Case PDH_CSTATUS_NO_COUNTER: errDescription = "The specified counter could not be found."
        Case PDH_CSTATUS_INVALID_DATA: errDescription = "The returned data is not valid."
        Case PDH_MEMORY_ALLOCATION_FAILURE: errDescription = "A PDH function could not allocate enough temporary memory to complete the operation. Close some applications or extend the pagefile and retry the function."
        Case PDH_INVALID_HANDLE: errDescription = "The handle is not a valid PDH object."
        Case PDH_INVALID_ARGUMENT: errDescription = "A required argument is missing or incorrect."
        Case PDH_FUNCTION_NOT_FOUND: errDescription = "Unable to find the specified function."
        Case PDH_CSTATUS_NO_COUNTERNAME: errDescription = "No counter was specified."
        Case PDH_CSTATUS_BAD_COUNTERNAME: errDescription = "Unable to parse the counter path. Check the format and syntax of the specified path."
        Case PDH_INVALID_BUFFER: errDescription = "The buffer passed by the caller is invalid."
        Case PDH_INSUFFICIENT_BUFFER: errDescription = "The requested data is larger than the buffer supplied. Unable to return the requested data."
        Case PDH_CANNOT_CONNECT_MACHINE: errDescription = "Unable to connect to the requested machine."
        Case PDH_INVALID_PATH: errDescription = "The specified counter path could not be interpreted."
        Case PDH_INVALID_INSTANCE: errDescription = "The instance name could not be read from the specified counter path."
        Case PDH_INVALID_DATA: errDescription = "The data is not valid."
        Case PDH_NO_DIALOG_DATA: errDescription = "The dialog box data block was missing or invalid."
        Case PDH_CANNOT_READ_NAME_STRINGS: errDescription = "Unable to read the counter and/or explain text from the specified machine."
        Case PDH_LOG_FILE_CREATE_ERROR: errDescription = "Unable to create the specified log file."
        Case PDH_LOG_FILE_OPEN_ERROR: errDescription = "Unable to open the specified log file."
        Case PDH_LOG_TYPE_NOT_FOUND: errDescription = "The specified log file type has not been installed on this system."
        Case PDH_NO_MORE_DATA: errDescription = "No more data is available."
        Case PDH_ENTRY_NOT_IN_LOG_FILE: errDescription = "The specified record was not found in the log file."
        Case PDH_DATA_SOURCE_IS_LOG_FILE: errDescription = "The specified data source is a log file."
        Case PDH_DATA_SOURCE_IS_REAL_TIME: errDescription = "The specified data source is the current activity."
        Case PDH_UNABLE_READ_LOG_HEADER: errDescription = "The log file header could not be read."
        Case PDH_FILE_NOT_FOUND: errDescription = "Unable to find the specified file."
        Case PDH_FILE_ALREADY_EXISTS: errDescription = "There is already a file with the specified file name."
        Case PDH_NOT_IMPLEMENTED: errDescription = "The function referenced has not been implemented."
        Case PDH_STRING_NOT_FOUND: errDescription = "Unable to find the specified string in the list of performance name and explain text strings."
        Case PDH_UNABLE_MAP_NAME_FILES: errDescription = "Unable to map to the performance counter name data files. The data will be read from the registry and stored locally."
        Case PDH_UNKNOWN_LOG_FORMAT: errDescription = "The format of the specified log file is not recognized by the PDH DLL."
        Case PDH_UNKNOWN_LOGSVC_COMMAND: errDescription = "The specified Log Service command value is not recognized."
        Case PDH_LOGSVC_QUERY_NOT_FOUND: errDescription = "The specified Query from the Log Service could not be found or could not be opened."
        Case PDH_LOGSVC_NOT_OPENED: errDescription = "The Performance Data Log Service key could not be opened. This may be due to insufficient privilege or because the service has not been installed."
        Case PDH_WBEM_ERROR: errDescription = "An error occured while accessing the WBEM data store.  The WBEM error code is contained in the LastError value."
        Case PDH_ACCESS_DENIED: errDescription = "Unable to access the desired machine or service. Check the permissions and authentication of the log service or the interactive user session against those on the machine or service being monitored."
        Case PDH_LOG_FILE_TOO_SMALL: errDescription = "The maximum log file size specified is too small to log the selected counters. No data will be recorded in this log file. Specify a smaller set of counters to log or a larger file size and retry this call."
        Case PDH_INVALID_DATASOURCE: errDescription = "Cannot connect to ODBC DataSource Name."
        Case PDH_INVALID_SQLDB: errDescription = "SQL Database does not contain a valid set of tables for Perfmon, use PdhCreateSQLTables."
        Case PDH_NO_COUNTERS: errDescription = "No counters were found for this Perfmon SQL Log Set."
        Case PDH_SQL_ALLOC_FAILED: errDescription = "Call to SQLAllocStmt failed with %1."
        Case PDH_SQL_ALLOCCON_FAILED: errDescription = "Call to SQLAllocConnect failed with %1."
        Case PDH_SQL_EXEC_DIRECT_FAILED: errDescription = "Call to SQLExecDirect failed with %1."
        Case PDH_SQL_FETCH_FAILED: errDescription = "Call to SQLFetch failed with %1."
        Case PDH_SQL_ROWCOUNT_FAILED: errDescription = "Call to SQLRowCount failed with %1."
        Case PDH_SQL_MORE_RESULTS_FAILED: errDescription = "Call to SQLMoreResults failed with %1."
        Case PDH_SQL_CONNECT_FAILED: errDescription = "Call to SQLConnect failed with %1."
        Case PDH_SQL_BIND_FAILED: errDescription = "Call to SQLBindCol failed with %1."
        Case PDH_CANNOT_CONNECT_WMI_SERVER: errDescription = "Unable to connect to the WMI server on requested machine."
        Case Else: errDescription = "No description available."
    End Select
    
    If NoMsgBox = False Then
        If errMsg = True Then
            If MessageBoxEx(&H0, strFunction & Chr$(13) & Chr$(10) & Chr$(13) & Chr$(10) & errDescription, "Error", MB_OK Or MB_ICONWARNING Or MB_SETFOREGROUND, 0) = 0 Then Failed "MessageBoxEx"
        End If
    End If
End Function
